django_test/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from movie import views as movieViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movieViews.home, name='home'),
    path('about/', movieViews.about, name='about'),
    path('signup/', movieViews.signup, name='signup'),
    path('news/', include('news.urls', namespace='news')),
    path('movie/', include('movie.urls', namespace='movie')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news, name='news'),
    # path('', views.NewsListView.as_view(), name='news'),
    # path('<int:news_id>', views.news_detail, name='news_detail'),
    # path('<int:news_id>/<int:year>/<int:month>/<int:day>/<slug:news>', views.news_detail, name='news_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:news_id>', views.news_detail, name='news_detail'),
    path('<int:news_id>/share/', views.news_share, name='news_share')
]

django_test/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                {% load static %}
                <img src="{% static 'images/movie.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
                Movies
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'news:news' %}">News</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out ({{ user.username }})</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex" role="search">
                    <input name="inputSearchMovie" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <svg class="bi" width="30" height="24">
                    <use xlink:href="{% url 'home' %}"></use>
                </svg>
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Rafael Mosquera - MosMad, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24">
                        <use xlink:href="#twitter"></use>
                    </svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24">
                        <use xlink:href="#instagram"></use>
                    </svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24">
                        <use xlink:href="#facebook"></use>
                    </svg></a></li>
        </ul>
    </footer>
</body>

</html>

django_test/templates/pagination.html
<nav>
    <ul class="pagination">
        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">First</span>
            </a>
            <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
        {% endif %}

        {% for num in page.paginator.page_range %}
            {% if page.number == num %}
                <strong>
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                </strong>
            {% elif num > page.number|add:"-3" and num < page.number|add:"3" %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        <strong>
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        </strong>
        
        {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page.number|add:'+1' }}">{{ page.number|add:'+1' }}</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">Last</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>