django_test/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from movie import views as movieViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movieViews.home, name='home'),
    path('about/', movieViews.about, name='about'),
    path('signup/', movieViews.signup, name='signup'),
    path('news/', include('news.urls', namespace='news')),
    path('movie/', include('movie.urls', namespace='movie')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('<int:movie_id>', views.detail, name='detail'),
    path('<int:movie_id>/create', views.create_review, name='create_review'),
    path('review/<int:review_id>', views.edit_review, name='edit_review'),
    path('review/<int:review_id>/delete', views.delete_review, name='delete_review'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news, name='news'),
    # path('', views.NewsListView.as_view(), name='news'),
    # path('<int:news_id>', views.news_detail, name='news_detail'),
    # path('<int:news_id>/<int:year>/<int:month>/<int:day>/<slug:news>', views.news_detail, name='news_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:news_id>', views.news_detail, name='news_detail'),
    path('<int:news_id>/share/', views.news_share, name='news_share')
]

movie/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User

# from django.contrib import auth


class Classification(models.Model):
    class ClassificationEnum(models.TextChoices):
        CLASS_A = 'A', 'Classification A'
        CLASS_B = 'B', 'Classification B'
        CLASS_C = 'C', 'Classification C'

    name = models.CharField(
        verbose_name="Classification name",
        choices=ClassificationEnum.choices,
        max_length=2, 
    )

    create_date = models.DateTimeField(auto_now_add=True, null=True)
    write_date = models.DateTimeField(auto_now_add=True, null=True)
    create_uid_classification = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='create_uid_classification')
    write_uid_classification = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='write_uid_classification')

    def __str__(self) -> str:
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=20, help_text="Genre of the movie")
    create_date = models.DateTimeField(auto_now_add=True, null=True)
    write_date = models.DateTimeField(auto_now_add=True, null=True)
    create_uid_genre = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='create_uid_genre')
    write_uid_genre = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='write_uid_genre')

    def __str__(self) -> str:
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=50)

    create_date = models.DateTimeField(auto_now_add=True, null=True)
    write_date = models.DateTimeField(auto_now_add=True, null=True)
    create_uid_director = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='create_uid_director')
    write_uid_director = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='write_uid_director')

    def __str__(self) -> str:
        return self.name
    

class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=Movies.Status.PUBLISHED)


class Movies(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='movie/images/')
    date = models.DateField(verbose_name='Fecha de Estreno')
    url = models.URLField(blank=True)

    # Genre should be Many2many
    genre = models.ForeignKey(Genre, null=True, on_delete=models.SET_NULL)

    clasificacion = models.ForeignKey(Classification, null=True, on_delete=models.SET_NULL)  # ForeignKey to create Many2one

    directors = models.ManyToManyField(Director)  # ManyToManyField to Many2many. through: to create a specific join table with extra info

    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    create_date = models.DateTimeField(auto_now_add=True)
    write_date = models.DateTimeField(auto_now=True)
    create_uid_movies = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='create_uid_movies')
    write_uid_movies = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='write_uid_movies')

    objects = models.Manager()  # Default manager
    published = PublishedManager()  # Custom manager

    class Meta:
        ordering  = ['-create_date']
        indexes = [
            models.Index(fields=['-create_date'])
        ]

    def __str__(self) -> str:
        return self.title
    

class Review(models.Model):
    text = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)  # Many2one
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE)  # Many2one
    watch_again = models.BooleanField()

    create_date = models.DateTimeField(auto_now_add=True, null=True)
    write_date = models.DateTimeField(auto_now_add=True, null=True)
    create_uid_review = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='create_uid_review')
    write_uid_review = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='write_uid_review')

    def __str__(self) -> str:
        return self.text
    

movie/forms.py
from typing import Any, Mapping
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import ModelForm, Textarea
from django.forms.utils import ErrorList
from .models import Review


class ReviewForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)

        self.fields["text"].widget.attrs.update({"class": "form-control"})
        self.fields["watch_again"].widget.attrs.update({"class": "form-check-input"})

    class Meta:
        model = Review
        fields = ["text", "watch_again"]
        labels = {"watch_again": ("Watch Again")}
        widgets = {
            "text": Textarea(attrs={"rows": 4}),
        }

movie/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.shortcuts import get_object_or_404, redirect

from .models import Movies, Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required



def home(request):
    # return HttpResponse('<h1>Home Page</h1>')
    search_term = request.GET.get('inputSearchMovie')
    if search_term:
        movies = Movies.objects.filter(title__icontains=search_term)
    else:
        movies = Movies.objects.all()
    return render(request, 'home.html', {'search_term': search_term, 'movies': movies})

def about(request):
    return HttpResponse('<h1>About Page</h1>')

def signup(request):
    email = request.GET.get('email')
    return render(request, 'signup.html', {'email': email})

def detail(request, movie_id: int):
    movie = get_object_or_404(Movies, pk=movie_id)
    reviews = Review.objects.filter(movie=movie)
    
    return render(request, 'detail.html', {'movie': movie, 'reviews': reviews})

@login_required
def create_review(request, movie_id: int):
    movie = get_object_or_404(Movies, pk=movie_id)
    if request.method == 'GET':
        context = {
            'form': ReviewForm, 
            'movie': movie
        }
        return render(request, 'create_review.html', context)
    else:
        try:
            form = ReviewForm(request.POST)
            new_review = form.save(commit=False)
            new_review.user = request.user
            new_review.movie = movie
            new_review.save()
            return redirect('movie:detail', new_review.movie.pk)
        except ValueError:
            return render(request, 'create_review.html', {'form': ReviewForm, 'error': 'Wrong data passed in'})

@login_required     
def edit_review(request, review_id: int):
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    if request.method == 'GET':
        form = ReviewForm(instance=review)
        return render(request, 'movie:edit_review.html', {'form':form, 'review': review})
    else:
        try:
            form = ReviewForm(request.POST, instance=review)
            form.save()
            return redirect('movie:detail', review.movie.pk)
        except ValueError:
            return render(request, 'edit_review.html', {'form':form, 'review': review, 'error':'Bad data in form'})

@login_required
def delete_review(request, review_id: int):
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    review.delete()
    return redirect('movie:detail', review.movie.pk)

movie/templates/create_review.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h5 class="card-title">Add Review for {{ movie.title }}</h5>
                {% if error %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error }}
                </div>
                {% endif %}
                <p class="card-text">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Add Review
                    </button>
                </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

movie/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ movie.image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{ movie.title }}</h5>
                <p class="card-text">{{ movie.description }}</p>
                <p class="card-text">
                    {% if movie.url %}
                    <a href="{{ movie.url }}" class="btn btn-primary">Movie Link</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a href="{% url 'movie:create_review' movie.id %}" class="btn btn-primary">
                        Add Review
                    </a>
                    {% endif %}
                </p>
                <p class="card-text"><small class="text-body-secondary">{{ movie.date }}</small></p>
                <hr />
                <h3>Reviews</h3>
                <ul class="list-group">
                    {% for review in reviews %}
                        <li class="list-group-item pb-3 pt-3">
                            <h5 class="card-title">
                                Review by {{ review.user.username }}
                            </h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                {{ review.date }}
                            </h6>
                            <p class="card-text">{{ review.text }}</p>
                            {% if user.is_authenticated and user == review.user %}
                            <a class="btn btn-primary me-2" href="{% url 'movie:edit_review' review.id %}">
                                Update
                            </a>
                            <a class="btn btn-danger" href="{% url 'movie:delete_review' review.id %}">
                                Delete
                            </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

movie/templates/edit_review.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
  <div class="row g-0">
    <div>
      <div class="card-body">
        <h5 class="card-title">
          Update Review for {{ review.movie.title }}
        </h5>
        {% if error %}
        <div class="alert alert-danger mt-3" role="alert">
          {{ error }}
        </div>
        {% endif %}
        <p class="card-text">
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">
            Update Review
          </button>
        </form>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

movie/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <!-- <form action="">
        <div class="mb-3">
            <label for="inputSearchMovie" class="form-label">Movie:</label>
            <input type="text" class="form-control" name="inputSearchMovie" aria-describedby="searchlHelp">
            <div id="searchlHelp" class="form-text">Search for the movie you want to review.</div>
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form> -->
    <p>Searching for {{ search_term }}</p>
    <div class="row row-cols-1 row-cols-md-3 g4">
        {% for movie in movies %}
            <div v-for="movie in movies" class="col">
                <div class="card" style="width: 18rem;">
                    <img src="{{ movie.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'movie:detail' movie.id %}">
                            <h5 class="card-title">{{ movie.title }}</h5>
                        </a>
                        <p class="card-text">{{ movie.description }}</p>
                        {% if movie.url %}
                            <a href="{{ movie.url }}" class="btn btn-primary">Movie Link</a>
                        {% endif %}
                        <p class="card-text"><small class="text-body-secondary">{{ movie.date }}</small></p>
                    </div>
                </div>
            </div> 
        {% endfor %}
    </div>
{% endblock content %}
<!-- <br/>
<br/>
<div class="container">
    <form action="{% url 'signup' %}">
        <div class="mb-3">
            <label for="email" class="form-label">Enter your email:</label>
            <input type="email" class="form-control" name="email">
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
</div> -->

movie/templates/signup.html
<!DOCTYPE html>
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Movies App</title>
    </head>

    <body>
        <div class="container">
            <h2>Added {{email}} to mailing list</h2>
            <a href="{%url 'home'%}">Home</a>
        </div>
    </body>
</html>