django_test/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from movie import views as movieViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movieViews.home, name='home'),
    path('about/', movieViews.about, name='about'),
    path('signup/', movieViews.signup, name='signup'),
    path('news/', include('news.urls', namespace='news')),
    path('movie/', include('movie.urls', namespace='movie')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news, name='news'),
    # path('', views.NewsListView.as_view(), name='news'),
    # path('<int:news_id>', views.news_detail, name='news_detail'),
    # path('<int:news_id>/<int:year>/<int:month>/<int:day>/<slug:news>', views.news_detail, name='news_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:news_id>', views.news_detail, name='news_detail'),
    path('<int:news_id>/share/', views.news_share, name='news_share')
]

news/models.py
from django.db import models

from django.urls import reverse

from django.contrib.auth.models import User



class News(models.Model):
    headline = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250, null=False, unique_for_date='date')
    body = models.TextField()
    date = models.DateField()

    create_date = models.DateTimeField(auto_now_add=True)
    write_date = models.DateTimeField(auto_now=True)
    create_uid = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='create_uid_news')
    write_uid_movies = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='write_uid_news')

    def __str__(self) -> str:
        return self.headline

    def get_absolute_url(self):
        # return reverse('news:news_detail', args=[self.pk])
        # return reverse('news:news_detail', args=[self.pk, self.date.year, self.date.month, self.date.day, self.slug])
        return reverse('news:news_detail', args=[self.date.year, self.date.month, self.date.day, self.slug])

news/forms.py
from django import forms


class EmailNewsForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    

news/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView

from django.core.mail import send_mail

import os

from .models import News
from .forms import EmailNewsForm


# class NewsListView(ListView):
#     """
#     Alternative news list view
#     """

#     # queryset = News.published.all()
#     model = News
#     context_object_name = 'newss'
#     paginate_by = 3
#     template_name = 'news.html'


def news(request):
    news_list = News.objects.all().order_by('-date')

    # pagination 3 news per page
    paginator = Paginator(news_list, 1)
    page_number = request.GET.get('page', 1)

    try:
        newss = paginator.page(page_number)
    except PageNotAnInteger:
        newss = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        newss = paginator.page(paginator.num_pages)

    return render(request, 'news.html', {'newss': newss})

# def news_detail(request, news_id: int):
def news_detail(request, year, month, day, news_id):
    # news = get_object_or_404(News, pk=news_id)
    # news = get_object_or_404(News, pk=news_id, slug=news_id, date__year=year, date__month=month, date__day=day)
    news = get_object_or_404(News, date__year=year, date__month=month, date__day=day, slug=news_id)

    return render(request, 'news_detail.html', {'news': news})


def news_share(request, news_id):
    news = get_object_or_404(News, pk=news_id)
    sent = False

    # Form submitted
    if request.method == 'POST':
        form = EmailNewsForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # ... send email
            news_url = request.build_absolute_uri(news.get_absolute_url())
            subject = f'{cd['name']} recommends yo read {news.headline}'
            message = f'News: {news.headline} at {news_url}'

            send_mail(subject, message, os.getenv('EMAIL_HOST_USER'), [cd['to']])

            sent = True

            print(f'{news_url=} - {subject=} - {message=}')
    else:
        form = EmailNewsForm()
    return render(request, 'news_share.html', {'form': form, 'news':news})

news/templates/news.html
{% extends 'base.html' %}
{% block title %}News{% endblock %}
{% block content %}
{% for news in newss %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <!-- <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div> -->
    <div class="col-md-8">
      <div class="card-body">
        
        <a href="{{ news.get_absolute_url }}">
          <h5 class="card-title">{{ news.headline }}</h5>
        </a>
        <p class="card-text">{{ news.body|truncatewords:2|linebreaks }}</p>
        <p class="card-text"><small class="text-body-secondary">{{ news.date }}</small></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{# % include 'pagination.html' with page=newss % #}
{% include 'pagination.html' with page=newss %}
{% endblock content %}

news/templates/news_detail.html
{% extends 'base.html' %}
{% block content %}

<div>
    <h1>{{ news.headline }}</h1>
    <p class="date">
        Published {{ news.date }} by {{ news.user }}
    </p>
    <p>{{news.body|linebreaks }}</p>
    <p>
        <a href="{% url 'news:news_share' news.id %}">
            Share this new
        </a>
    </p>
</div>

{% endblock %}

news/templates/news_share.html
{% extends 'base.html' %}
{% block title %} Share news {% endblock %}
{% block content %}
    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>
            "{{ news.headline }} was sent to {{ form.cleaned_datea.to }}"
        </p>
    {% else %}
        <h1>Share "{{ news.headline }} by email"</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send email">
        </form>
    {% endif %}
{% endblock %}